{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "prom-metrics.fullname" . }}
  namespace: {{ include "prom-metrics.namespace" . }}
  labels:
    {{- include "prom-metrics.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "prom-metrics.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - ports:
        - port: {{ .Values.containerPort }}
          protocol: TCP
      {{- with .Values.networkPolicy.ingressFrom }}
      from:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - ports:
        - port: {{ .Values.networkPolicy.prometheusPort }}
          protocol: TCP
      {{- with .Values.networkPolicy.prometheusTo }}
      to:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
