apiVersion: v1
kind: Service
metadata:
  name: {{ include "prom-metrics.fullname" . }}
  namespace: {{ include "prom-metrics.namespace" . }}
  labels:
    {{- include "prom-metrics.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "prom-metrics.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
